### ISSUE TITLE
Collect `Storage` details (name, model, size, etc) on discovery

### ISSUE THREAD

**Issue by defo89** [ironcore-dev/metal-operator#142]
# Summary

For later install on disk feature we need to discover storage devices and their details and add it to `Server` status.

**Comment by stefanhipfel** [comment]
I would take that if it’s ok with you, since i am also working on install from disk

**Comment by afritzler** [comment]
I would suggest we extend the API first by defining what should go into `Server.Status.Storage`. As @defo89 mentioned name, model, size, PCI/bus information?

Then I would go an try to read this info out via BMC Redfish first. If we realize that this is not enough we could extend `metalprobe` to do that extraction for us on OS level. The controller manager can then be started with `--server-storage-source={Redfish,OS,...}` where Redfish is the default option.

**Comment by stefanhipfel** [comment]
We could use the same fields as before:
```
// Storage defines the details of one storage device
type Storage struct {
	// Name is the name of the storage interface.
	Name string `json:"name,omitempty"`
	// Rotational specifies whether the storage device is rotational.
	Rotational bool `json:"rotational,omitempty"`
	// Type specifies the type of the storage device.
	Type DiskType `json:"type,omitempty"`
	// SizeBytes specifies the size of the storage device in bytes.
	SizeBytes Capacity `json:"sizeBytes,omitempty"`
	// Vendor specifies the vendor of the storage device.
	Vendor string `json:"vendor,omitempty"`
	// Model specifies the model of the storage device.
	Model string `json:"model,omitempty"`
}
```
