### ISSUE TITLE
Deprecate `.spec.uuid` in favor of `.spec.systemUUID`

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/metal-operator#144]
# Summary

Since the system uuid is currently stored in the `Server` spec under `uuid` and leads to some confusion regarding the meaning of this field we might want to rename it. Suggestion would be to use `.spec.systemUUID` instead of `.spec.uuid`.

For backward compatibility we should deprecate the old field name and set both fields for now. Later we can set it to an empty `string` and remove it.

**Comment by stefanhipfel** [comment]
`+kubebuilder:deprecatedversion` can only bet set at the crd level, not field level.

so as far is I understand, one can only put it like this:

`//+kubebuilder:deprecatedversion:warning="metal.ironcore.dev/v1alpha1 ServerSpec.UUID will be deprecated in version ...."`
