### ISSUE TITLE
`ServerClaim` does not propagate power state to `Server`

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/metal-operator#61]
**Describe the bug**

Once a `Server` has been claimed and reserved, the change of the `Power` field in the `ServerClaim` is not propagated to the `Server` resource due to an early exit in the claim reconciliation loop. This posts a problem as you can not power of a `Server` via it's claim.

**Comment by stefanhipfel** [comment]
What is the exact purpose of setting the powerState in the serverClaim?

do I want to have the powerState applied after my server has booted the desired bootconfig?

Is this the only way a "customer" which has claimed a server to power cycle his server?

**Comment by afritzler** [comment]
Yes that is exactly the intention here: The owner of a `ServerClaim` can typically not modify the `Server` object directly.

**Comment by afritzler** [comment]
Fixed with https://github.com/ironcore-dev/metal-operator/pull/50
