### ISSUE TITLE
Dell IDRAC9: BIOS reconfiguration job triggered on each one time boot override

### ISSUE THREAD

**Issue by defo89** [ironcore-dev/metal-operator#81]
**Describe the bug**
Each time `"BootSourceOverrideMode": "UEFI"` is set - despite it's already configured - config job is queued and applied, making the server to reboot twice (1st boot to reconfigure BIOS).

**To Reproduce**
Steps to reproduce the behavior e.g. provide example action definition.

**Expected behavior**
Probably 2 options to fix:
1. Investigate with Dell why reconfig config job is done despite it's already being configured (no config diff)
2. Operator reads out current setting and does not apply `"BootSourceOverrideMode": "UEFI"`, but rather just sets `BootSourceOverrideTarget` and `BootSourceOverrideEnabled`.

**Screenshots**
Configuration - BIOS settings

![image](https://github.com/user-attachments/assets/99a9fc66-9a5a-4c82-a515-694888708443)

On 1st reboot:

![image](https://github.com/user-attachments/assets/1ba1b0f8-98a0-4748-ac3a-edabce5480d8)

![image](https://github.com/user-attachments/assets/318c6bc0-e513-4eba-9c36-045720bb73ef)

**Additional context**
Encountered this on 2 available lab servers:
```
Model: PowerEdge R660
BIOS Version: 1.6.6
iDRAC Firmware Version: 7.10.30.05
```

**Comment by stefanhipfel** [comment]
added it to our internal GCS Compute DELL board

**Comment by defo89** [comment]
@afritzler @hardikdr the Dell boots into lifecycle controller and causes extra delay/instability if we always set [redfish.UEFIBootSourceOverrideMode](https://github.com/ironcore-dev/metal-operator/blob/main/bmc/redfish.go#L113)

Proposal for now would be to read out the setting and only set it if's not equal to UEFI. Later on, I rather see this kind of parameter part of BIOS setting.
